owner: IsThisGreatOrWhat
repo: OctEspoCRM-Uptime

sites:
  - name: Octigence EspoCRM
    url: https://espo.octigence.com/

assignees:
  - IsThisGreatOrWhat

status-website:
  baseUrl: /OctEspoCRM-Uptime
  name: Octigence EspoCRM Status
